### ISSUE TITLE
NUDomain object has no advertise_criteria attribute

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspk-python#11]
@pdellaert hi,
4.0.7 && 4.0.8

In GUI we can instantiate Hub L3 domain w/ specific advertise criteria
> ![image](https://cloud.githubusercontent.com/assets/5679861/25083051/64463746-235d-11e7-82fb-c9f468cb2992.png)

This results in API call containing `advertiseCriteria` attr

> ![image](https://cloud.githubusercontent.com/assets/5679861/25083060/7a7f3e86-235d-11e7-9919-c6ae08d3a6e2.png)

yet it seems like [domain specification](https://github.com/nuagenetworks/vsd-api-specifications/blob/4.0/domain.spec) and VSPK has no such attribute specified for nudomain object, thus we cant configure this particular property of a domain

_Edit_: probably this should be rather opened under vsd-api-specifications

**Comment by pdellaert** [comment]
Hi @hellt,

Thank you for opening this. I'm reporting this back and making sure this is fixed in the next releases.

 yes it is better to be moved to vsd-api-specifications, but it's fine for this issue, no need to move :).

Cheers!

**Comment by hellt** [comment]
Hi,
tested with 5.0.1, works fine, thanks. Closing this issue.
