### ISSUE TITLE
vspk==4.0.11 is missing

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspk-python#17]
Hi all,
can you please generate 4.0.11 and upload it to pypi?

**Comment by pdellaert** [comment]
yes, we're working on that, @little-dude

**Comment by little-dude** [comment]
It _is_ there, I uploaded it yesterday: https://pypi.python.org/pypi/vspk/4.0.11

**Comment by hellt** [comment]
Thanks!

**Comment by pdellaert** [comment]
Thanks @little-dude !! Should have checked :)
