### ISSUE TITLE
Should the "BEGIN_POLICY_CHANGES" job wait for all policies to be successfully copied from LIVE to DRAFT?  

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspk-python#23]
Hi @pdellaert 
Is it possible that "BEGIN_POLICY_CHANGES" job returned `SUCCESS` status, but not all policies copied to `DRAFT` at that time?

A bug has been reported to me claiming that policy entry was non-existent in DRAFT mode right after the domain was put into policy editing mode? We will try to recreate this one with logs enabled, but I wanted to check upfront, maybe it is expected and some timeout should be put in place before trying to modify sec policy objects after moving into policy editing mode.

**Comment by pdellaert** [comment]
@hellt, a job with command `BEGIN_POLICY_CHANGES` should not return `SUCCESS` until all policies have been copied to `DRAFT` status. As long as copying is not finished, the job should remain in status `RUNNING`.

Somehow, i expect that whomever is filing the bug, is actually not waiting until the status is `SUCCESS`

**Comment by hellt** [comment]
Ok, understood. Will see if this issue will be reported ever again

On Tue, Nov 21, 2017 at 2:36 PM, Philippe Dellaert <notifications@github.com

**Comment by pdellaert** [comment]
Of course, if you actually see this is not the case, then we have a bug :), i just haven't heard of any case where this is not happening correctly, up until now.

**Comment by hellt** [comment]
most probably this issue had some other root causes. Will watch closely on
this.

/close

On Tue, Nov 21, 2017 at 2:55 PM, Philippe Dellaert <notifications@github.com
