### ISSUE TITLE
NUCSNATPool / NUPSNATPool Objects Missing Parameters

### ISSUE THREAD

**Issue by brncoguz** [nuagenetworks/vspk-python#31]
Hi,

Seemingly `NUCSNATPool` and  `NUPSNATPool` objects don't have the `name` and some other parameters in the vspk 5.2.3, even though I'm specifying the name parameter, I'm getting this error:
```
BambouHTTPError: [HTTP 409(Conflict)] [{u'property': u'name', u'descriptions': [{u'description': u'This value cannot be null', u'title': u'Invalid input. Value cannot be null'}]}]
```

also in the 5.2.3 vspk code (nupsnatpool.py) there are only these two parameters exist:
```
self._end_address = None
self._start_address = None
        
self.expose_attribute(local_name="end_address", remote_name="endAddress", attribute_type=str, is_required=True, is_unique=False)
self.expose_attribute(local_name="start_address", remote_name="startAddress", attribute_type=str, is_required=True, is_unique=False)
```

here are the vsd api URLs:
https://github.com/nuagenetworks/vsd-api-specifications/blob/master/csnatpool.spec
https://github.com/nuagenetworks/vsd-api-specifications/blob/master/psnatpool.spec

I also tried on 5.3.3, there is no problem on that release, seems like it's fixed on one of the newer release.

**Comment by pdellaert** [comment]
Closing, as this is fixed in 5.3.3 and currently we do not plan to re-release a 5.2.3 VSPK
