### ISSUE TITLE
vsd cli python version

### ISSUE THREAD

**Issue by marcowenwolf** [nuagenetworks/vspk-python#38]
Please confirm if vsd cli is also working with python3. In python2 vsd cli is working. In python 3 I got a No module name 'commands' error:

(testautomation) marcwolf@laptop:~/git/gvp-sdn-vm-stuck> vsd
Traceback (most recent call last):
  File "/home/marcwolf/venvs/testautomation/bin/vsd", line 11, in <module>
    load_entry_point('vspk', 'console_scripts', 'vsd')()
  File "/home/marcwolf/venvs/testautomation/lib/python3.6/site-packages/vspk/cli/cli.py", line 136, in main
    from commands import CLICommand
ModuleNotFoundError: No module named 'commands'

**Comment by pdellaert** [comment]
@marcowenwolf , sorry for the late reply. But yes, this is confirmed. VSD CLI only works on Python 2.7 as of now (which is something we plan to fix, but will take some time)

**Comment by marcowenwolf** [comment]
Do you already have a idea when vsd cli will be ported to python3?
