### ISSUE TITLE
Missing job fetcher in nuvirtualfirewallpolicy.py for API 5.0 and 6.0

### ISSUE THREAD

**Issue by ghost** [nuagenetworks/vspk-python#39]
The class NUVirtualFirewallPolicy is missing the jobs fetcher, preventing to create jobs related to Virtual Firewall Policies

Basically we need,
- an import:
from .fetchers import NUJobsFetcher

- and define self.jobs in the `def __init__`:
self.jobs = NUJobsFetcher.fetcher_with_object(parent_object=self, relationship="child")

**Comment by pdellaert** [comment]
Closing this in favour of nuagenetworks/vsd-api-specifications#75
