### ISSUE TITLE
README contains wrong link to docs

### ISSUE THREAD

**Issue by Mierdin** [nuagenetworks/vspk-python#4]
README links to http://nuagenetworks.github.io/sdkdoc/index.html, which produces a 404.

Should link to http://nuagenetworks.github.io/documentation/index.html, I think?

**Comment by little-dude** [comment]
Thanks.
I cannot just edit the README because it is automatically generated.
It should be fixed for good when we regenerate the vspk.
ref: https://github.com/nuagenetworks/vspkgenerator/commit/f5e08553f62e8b0a51b76df5360bd232fcc56358

**Comment by CyrilPeponnet** [comment]
Fixed in latest release.
