### ISSUE TITLE
setup.py vspk version is not changing

### ISSUE THREAD

**Issue by pdellaert** [nuagenetworks/vspk-python#6]
https://github.com/nuagenetworks/vspk-python/blob/master/setup.py#L51

This is still 4.0.5, while we are at 4.0.6. Is there a way of updating this during auto-generation of the vspk?

**Comment by greenpau** [comment]
@pdellaert , :+1:

**Comment by little-dude** [comment]
my bad yeah. will fix.

**Comment by greenpau** [comment]
> my bad yeah. will fix.

@little-dude, How about `pip install vspk==<VSPK_VERSION>` from pypi? :smile:

**Comment by little-dude** [comment]
Updated it for 4.0R7.
@greenpau you can install vspk from pypi like this already ;)
