### ISSUE TITLE
Python 3 support is missing

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspk-python#9]
Underlying [Bambou](https://pypi.python.org/pypi/bambou/2.1.2) package is written with py2 syntax, thus Python3 cannot be used with VSPK which is a huge restriction in 2017.

**Comment by hellt** [comment]
With 5.2.2 release did py3 support reach GA status?

**Comment by pdellaert** [comment]
Provided in the bambou 3.0 release, which is the default bambou release used in 5.2.2 and above
